<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Scalar.AspNetCore" />

        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />

        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        
        <PackageReference Include="Serilog.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DictionaryWorker\DictionaryWorker.csproj" />
      <ProjectReference Include="..\Enrolly.EduDictionary.Application\Enrolly.EduDictionary.Application.csproj" />
      <ProjectReference Include="..\..\..\Shared\Enrolly.Shared\Enrolly.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
