using DictionaryWorker.DTOs;
using Enrolly.EduDictoinary.Domain.Entities;
using Riok.Mapperly.Abstractions;

namespace Enrolly.EduDictionary.Application.Mappings;

//autogenerated mapper (DocTypeDto <-> DocType)
[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.None)]
public partial class DocumentTypeMapper
{
    public partial DocumentTypeDto ToDto(DocumentType? model);
    public partial IEnumerable<DocumentTypeDto> ToDtos(IEnumerable<DocumentType>? models);
    
    public partial DocumentType FromDto(DocumentTypeDto? dto);
    public partial IEnumerable<DocumentType> FromDtos(IEnumerable<DocumentTypeDto> dtos);
}