using DictionaryWorker.DTOs;
using Enrolly.EduDictionary.Domain.DTOs;
using Enrolly.EduDictionary.Domain.Entities;
using Enrolly.EduDictoinary.Domain.Entities;
using Riok.Mapperly.Abstractions;

namespace Enrolly.EduDictionary.Application.Mappings;

//autogenerated mapper (DocTypeDto <-> DocType)
[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.None)]
public partial class DocumentTypeMapper
{
    [MapProperty(nameof(DocumentType.CreatedAt), nameof(DocumentTypeDto.CreateTime))]
    public partial DocumentTypeDto ToDto(DocumentType? model);
    public partial IEnumerable<DocumentTypeDto> ToDtos(IEnumerable<DocumentType>? models);
    
    [MapProperty("EducationLevel.Id", "EducationLevelId")]
    [MapProperty(nameof(DocumentTypeDto.CreateTime), nameof(DocumentType.CreatedAt))]
    public partial DocumentType FromDto(DocumentTypeDto? dto);
    public partial IEnumerable<DocumentType> FromDtos(IEnumerable<DocumentTypeDto> dtos);


    private partial EducationLevelDto ToDto(EducationLevel? model);
    private partial IEnumerable<EducationLevelDto> ToDtos(IEnumerable<EducationLevel>? models);
    
    private partial EducationLevel FromDto(EducationLevelDto? dto);
    private partial IEnumerable<EducationLevel> FromDtos(IEnumerable<EducationLevelDto> dtos);
}