using DictionaryWorker.DTOs;
using Enrolly.EduDictoinary.Domain.Entities;
using Riok.Mapperly.Abstractions;

namespace Enrolly.EduDictionary.Application.Mappings;

//autogenerated mapper (FacultyDto <-> Faculty)
[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.None)]
public partial class FacultyMapper
{
    [MapProperty(nameof(Faculty.CreatedAt), nameof(FacultyDto.CreateTime))]   
    public partial FacultyDto ToDto(Faculty? model);
    public partial IEnumerable<FacultyDto> ToDtos(IEnumerable<Faculty>? models);
    
    [MapProperty(nameof(FacultyDto.CreateTime), nameof(Faculty.CreatedAt))]
    public partial Faculty FromDto(FacultyDto? dto);
    public partial IEnumerable<Faculty> FromDtos(IEnumerable<FacultyDto> dtos);
}
