// <auto-generated />
using System;
using Enrolly.Accounts.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enrolly.Accounts.Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260522195819_AddedAdmissionStatusColumn")]
    partial class AddedAdmissionStatusColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicantManager", b =>
                {
                    b.Property<Guid>("ManagersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PendingApplicantsId")
                        .HasColumnType("uuid");

                    b.HasKey("ManagersId", "PendingApplicantsId");

                    b.HasIndex("PendingApplicantsId");

                    b.ToTable("ApplicantManager");
                });

            modelBuilder.Entity("Enrolly.Accounts.Domain.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CitizenshipId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActiveAdmission")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CitizenshipId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Enrolly.Accounts.Domain.Entities.Citizenship", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("citizenship", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsoCode = "RU",
                            Name = "Россия"
                        },
                        new
                        {
                            Id = 2,
                            IsoCode = "US",
                            Name = "США"
                        },
                        new
                        {
                            Id = 3,
                            IsoCode = "DE",
                            Name = "Германия"
                        },
                        new
                        {
                            Id = 4,
                            IsoCode = "FR",
                            Name = "Франция"
                        },
                        new
                        {
                            Id = 5,
                            IsoCode = "GB",
                            Name = "Великобритания"
                        },
                        new
                        {
                            Id = 6,
                            IsoCode = "IT",
                            Name = "Италия"
                        },
                        new
                        {
                            Id = 7,
                            IsoCode = "ES",
                            Name = "Испания"
                        },
                        new
                        {
                            Id = 8,
                            IsoCode = "CN",
                            Name = "Китай"
                        },
                        new
                        {
                            Id = 9,
                            IsoCode = "JP",
                            Name = "Япония"
                        },
                        new
                        {
                            Id = 10,
                            IsoCode = "IN",
                            Name = "Индия"
                        },
                        new
                        {
                            Id = 11,
                            IsoCode = "BR",
                            Name = "Бразилия"
                        },
                        new
                        {
                            Id = 12,
                            IsoCode = "CA",
                            Name = "Канада"
                        },
                        new
                        {
                            Id = 13,
                            IsoCode = "AU",
                            Name = "Австралия"
                        },
                        new
                        {
                            Id = 14,
                            IsoCode = "MX",
                            Name = "Мексика"
                        },
                        new
                        {
                            Id = 15,
                            IsoCode = "KR",
                            Name = "Южная Корея"
                        },
                        new
                        {
                            Id = 16,
                            IsoCode = "NL",
                            Name = "Нидерланды"
                        },
                        new
                        {
                            Id = 17,
                            IsoCode = "SE",
                            Name = "Швеция"
                        },
                        new
                        {
                            Id = 18,
                            IsoCode = "NO",
                            Name = "Норвегия"
                        },
                        new
                        {
                            Id = 19,
                            IsoCode = "CH",
                            Name = "Швейцария"
                        },
                        new
                        {
                            Id = 20,
                            IsoCode = "BE",
                            Name = "Бельгия"
                        },
                        new
                        {
                            Id = 21,
                            IsoCode = "AT",
                            Name = "Австрия"
                        },
                        new
                        {
                            Id = 22,
                            IsoCode = "PL",
                            Name = "Польша"
                        },
                        new
                        {
                            Id = 23,
                            IsoCode = "TR",
                            Name = "Турция"
                        },
                        new
                        {
                            Id = 24,
                            IsoCode = "EG",
                            Name = "Египет"
                        },
                        new
                        {
                            Id = 25,
                            IsoCode = "IL",
                            Name = "Израиль"
                        },
                        new
                        {
                            Id = 26,
                            IsoCode = "AE",
                            Name = "ОАЭ"
                        },
                        new
                        {
                            Id = 27,
                            IsoCode = "SA",
                            Name = "Саудовская Аравия"
                        },
                        new
                        {
                            Id = 28,
                            IsoCode = "ZA",
                            Name = "ЮАР"
                        },
                        new
                        {
                            Id = 29,
                            IsoCode = "AR",
                            Name = "Аргентина"
                        },
                        new
                        {
                            Id = 30,
                            IsoCode = "CL",
                            Name = "Чили"
                        },
                        new
                        {
                            Id = 31,
                            IsoCode = "CO",
                            Name = "Колумбия"
                        },
                        new
                        {
                            Id = 32,
                            IsoCode = "PE",
                            Name = "Перу"
                        },
                        new
                        {
                            Id = 33,
                            IsoCode = "VE",
                            Name = "Венесуэла"
                        },
                        new
                        {
                            Id = 34,
                            IsoCode = "MY",
                            Name = "Малайзия"
                        },
                        new
                        {
                            Id = 35,
                            IsoCode = "SG",
                            Name = "Сингапур"
                        },
                        new
                        {
                            Id = 36,
                            IsoCode = "TH",
                            Name = "Таиланд"
                        },
                        new
                        {
                            Id = 37,
                            IsoCode = "VN",
                            Name = "Вьетнам"
                        },
                        new
                        {
                            Id = 38,
                            IsoCode = "ID",
                            Name = "Индонезия"
                        },
                        new
                        {
                            Id = 39,
                            IsoCode = "PH",
                            Name = "Филиппины"
                        },
                        new
                        {
                            Id = 40,
                            IsoCode = "UA",
                            Name = "Украина"
                        },
                        new
                        {
                            Id = 41,
                            IsoCode = "KZ",
                            Name = "Казахстан"
                        },
                        new
                        {
                            Id = 42,
                            IsoCode = "BY",
                            Name = "Беларусь"
                        },
                        new
                        {
                            Id = 43,
                            IsoCode = "FI",
                            Name = "Финляндия"
                        },
                        new
                        {
                            Id = 44,
                            IsoCode = "DK",
                            Name = "Дания"
                        },
                        new
                        {
                            Id = 45,
                            IsoCode = "PT",
                            Name = "Португалия"
                        },
                        new
                        {
                            Id = 46,
                            IsoCode = "GR",
                            Name = "Греция"
                        },
                        new
                        {
                            Id = 47,
                            IsoCode = "IE",
                            Name = "Ирландия"
                        },
                        new
                        {
                            Id = 48,
                            IsoCode = "CZ",
                            Name = "Чехия"
                        },
                        new
                        {
                            Id = 49,
                            IsoCode = "HU",
                            Name = "Венгрия"
                        },
                        new
                        {
                            Id = 50,
                            IsoCode = "RO",
                            Name = "Румыния"
                        });
                });

            modelBuilder.Entity("Enrolly.Accounts.Domain.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Enrolly.Accounts.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f8fad5b-d9cb-469f-a165-70867728950e",
                            Email = "ivanovdanil.hits2024@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVANOVDANIL.HITS2024@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEK/Rx9lXaMVl2XRpYwE8soOLgg4u8mECM985xTPE+23pqnopjLqH1iyxEVhE0Y8c8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConcurrencyStamp = "222cf406-7901-45e0-a625-2fd0f8ab2b27",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicantManager", b =>
                {
                    b.HasOne("Enrolly.Accounts.Domain.Entities.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enrolly.Accounts.Domain.Entities.Applicant", null)
                        .WithMany()
                        .HasForeignKey("PendingApplicantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Enrolly.Accounts.Domain.Entities.Applicant", b =>
                {
                    b.HasOne("Enrolly.Accounts.Domain.Entities.Citizenship", "Citizenship")
                        .WithMany()
                        .HasForeignKey("CitizenshipId");

                    b.HasOne("Enrolly.Accounts.Domain.Entities.User", "Account")
                        .WithOne("ApplicantProfile")
                        .HasForeignKey("Enrolly.Accounts.Domain.Entities.Applicant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Citizenship");
                });

            modelBuilder.Entity("Enrolly.Accounts.Domain.Entities.Manager", b =>
                {
                    b.HasOne("Enrolly.Accounts.Domain.Entities.User", "Account")
                        .WithOne("ManagerProfile")
                        .HasForeignKey("Enrolly.Accounts.Domain.Entities.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Enrolly.Accounts.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Enrolly.Accounts.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enrolly.Accounts.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Enrolly.Accounts.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Enrolly.Accounts.Domain.Entities.User", b =>
                {
                    b.Navigation("ApplicantProfile");

                    b.Navigation("ManagerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
