<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
      <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
      <PackageVersion Include="Scalar.AspNetCore" Version="2.0.9" />

      <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
      <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
      <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
      <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
      
      <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
      
      <PackageVersion Include="Yarp.ReverseProxy" Version="2.2.0" />

      <PackageVersion Include="MailKit" Version="4.15.0"/>
      <PackageVersion Include="MimeKit" Version="4.15.1"/>
  </ItemGroup>
</Project>