// <auto-generated />
using System;
using Enrolly.Admissions.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enrolly.Admissions.Infrastructure.Migrations
{
    [DbContext(typeof(AdmissionsDbContext))]
    [Migration("20260506174000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdmissionStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ManagerId");

                    b.ToTable("admission", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.AdmissionProgram", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("ProgramId", "AdmissionId");

                    b.HasIndex("AdmissionId");

                    b.ToTable("admission_program", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("applicant", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EducationLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("EducationLevelId");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("education_level", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("faculty", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("manager", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EducationLevelId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("FacultyId");

                    b.ToTable("program", (string)null);
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Admission", b =>
                {
                    b.HasOne("Enrolly.Admissions.Domain.Entities.Applicant", "Applicant")
                        .WithMany("Admissions")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enrolly.Admissions.Domain.Entities.Manager", null)
                        .WithMany("PendingAdmissions")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.AdmissionProgram", b =>
                {
                    b.HasOne("Enrolly.Admissions.Domain.Entities.Admission", null)
                        .WithMany("Programs")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enrolly.Admissions.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Document", b =>
                {
                    b.HasOne("Enrolly.Admissions.Domain.Entities.Applicant", null)
                        .WithMany("Documents")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enrolly.Admissions.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId");

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.EducationLevel", b =>
                {
                    b.HasOne("Enrolly.Admissions.Domain.Entities.Document", null)
                        .WithMany("NextEducationLevels")
                        .HasForeignKey("DocumentId");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Manager", b =>
                {
                    b.HasOne("Enrolly.Admissions.Domain.Entities.Applicant", null)
                        .WithMany("Managers")
                        .HasForeignKey("ApplicantId");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Program", b =>
                {
                    b.HasOne("Enrolly.Admissions.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId");

                    b.HasOne("Enrolly.Admissions.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.Navigation("EducationLevel");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Admission", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Applicant", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Documents");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Document", b =>
                {
                    b.Navigation("NextEducationLevels");
                });

            modelBuilder.Entity("Enrolly.Admissions.Domain.Entities.Manager", b =>
                {
                    b.Navigation("PendingAdmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
