<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Riok.Mapperly"/>
        <PackageReference Include="Microsoft.Extensions.Http" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Enrolly.Shared.Logging\Enrolly.Shared.Logging.csproj" />
      <ProjectReference Include="..\Enrolly.EduDictionary.Domain\Enrolly.EduDictionary.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DTOs\" />
    </ItemGroup>
</Project>
