<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Enrolly.Contracts\Enrolly.Contracts.csproj" />
      <ProjectReference Include="..\..\..\Shared\Enrolly.Shared\Enrolly.Shared.csproj" />
      <ProjectReference Include="..\Enrolly.Accounts.Domain\Enrolly.Accounts.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
      <PackageReference Include="Riok.Mapperly" />
      <PackageReference Include="MassTransit " />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DependencyInjection\" />
    </ItemGroup>

</Project>
